#!/usr/bin/bash
ARTIST=$1

curl -X "GET" "https://api.spotify.com/v1/search?q=$1&type=artist" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAuTaWKvo_vQOlWZql5-dkTcwiQrHsbRmRD_WgKWJn-BTWBL1-AfjohX-iL_yk1-B2bMFMLg-9cNACcAIrZaD-9Wpxo_XBioZRhQnPq6P7N-g3Ilnm0zhSQiGO0gtl0uqi7kflhG9RJ2L9utXqQL8JXvi4IVF8KPJepHwrUP02fSw" | jq '.artists | .items[] | .id'
