#!/bin/sh

[ -f "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper Changed."

[ -d $1 ] && mv "$(find "$1"/*.{jpg,png} -type f | shuf -n 1)" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Random Wallpaper Chosen."

xwallpaper --stretch ~/.config/wall.png
